### ISSUE TITLE
Documentation: Make list of better ways to solve them in ReadMe

### ISSUE THREAD

**Issue by freemin7** [JuliaDiffEq/DiffEqApproxFun.jl#14]

**Comment by ChrisRackauckas** [comment]
This repo is pretty much deprecated. It's being replaced by the types just working.

**Comment by freemin7** [comment]
Ok, it would find it nice if people were given a small pointer how it is done now that the package is gone.

**Comment by ChrisRackauckas** [comment]
We need to fix up these benchmarks, but the direct fixed length version is shown here: https://benchmarks.sciml.ai/html/MOLPDE/burgers_spectral_wpd.html
